language: android

env:
  global:
  - ANDROID_API_LEVEL = 28
  - ANDROID_BUILD_TOOLS_VERSION = 28.0.3
  
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-x86-android-26
    #- sys-img-armeabi-v7a-android-17
    
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-52d11cd2'
    - 'google-gdk-license-.+'
    
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

# The actual script which would be executed when a build is initiated.
script:
  - "./gradlew assembleRelease --scan -s"    
