language: android
env:
  global:
  - ANDROID_API_LEVEL = 28
  - ANDROID_BUILD_TOOLS_VERSION = 28.0.3
android:
  components:
  - tools
  - platform-tools
  - extra-android-support
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - android-sdk-preview-license-52d11cd2
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_b4ee753593fc_key -iv $encrypted_b4ee753593fc_iv
  -in api-8830862669087182115-516792-6e644895026f.json.enc -out app/api-8830862669087182115-516792-6e644895026f.json
  -d
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "build-tools;28.0.3"
script:
- "./gradlew assembleRelease publishApkRelease --scan -s"
